config/routes.rb
ChessMaster::Application.routes.draw do
  resources :games

  resources :boards
  
  match 'play/game(/:slug)' => 'play#game', :as => 'short_game'
  match 'play/register' => 'play#register'
  match 'play/move' => 'play#move'
  match 'play/' => 'play#welcome'
  
  root :to => 'play#welcome'

end

app/controllers/play_controller.rb
class PlayController < ApplicationController
  layout 'player'

  def welcome
    @game = Game.new
  end
  
  def game
    @game = Game.where(:slug => params[:slug]).first
    raise ActionController::RoutingError.new('Game not found') if @game.nil?
    @board = @game.boards.last
    @board.rotate if @game.user_color == 'black'
  end
  
  def move
    game = Game.where(:slug => params[:slug]).first
    begin
      raise "It's not your turn!" unless game.user_turn
      game.move(params[:from], params[:to])
      
    rescue MoveError
      message = $!.message
    else
      begin
        DeepBlue.queue_game(game.id)
      rescue
        message = "Move accepted, but i couldn't reach deep blue. Don't worry, he'll look at your game when he's back"
      else
        message = "Move accepted! Deep blue is thinking. Refresh the page to see the result."
      end
    end
    redirect_to short_game_path(:slug => game.slug), :notice => message
  end
  
  def register
    game = Game.new
    game.user_name = params[:game]
    
    if game.save
      unless game.user_turn
        begin
          DeepBlue.queue_game game.id 
        rescue
          message = "Game started. Deep blue could not be reached, but he'll look at it when he's back"
        else
          message = "Game started. Deep blue is thinking. Refresh the page to see the result."
        end
      end  
      redirect_to short_game_path(:slug => game.slug), :notice => message
    else
      redirect_to play_url, :notice => "Could not start game!"
    end
  end
end

app/views/play/game.html.erb
<% if notice %>
  <div class="infobar"><%= notice %></div>
<% end %>
<div class='input_form wide'>
  <h2>
    <% if @game.user_turn %>
      It is your turn (<%=@game.user_color.capitalize%>)
    <% else %>
      It is the computer's turn (<%=@game.computer_color.capitalize%>)
    <% end %>
  </h2>
  <div class="field">
    <%= render :partial => "shared/chess_board", :locals => {:board => @board } %>
  </div>
  <% if @game.user_turn %>
    <div class="move_field">
    <%= form_tag play_move_url do %>
      <%= label_tag :move, 'Your move:' %><br />
      <%=hidden_field_tag(:slug, @game.slug) %>
      From: <%= text_field_tag(:from, nil, :class => 'small') %>
      To:  <%= text_field_tag(:to, nil, :class => 'small') %><br/><br/>
      <%= submit_tag("Play move") %>
    <% end %>
  </div>
<% end %>
</div>

app/views/play/welcome.html.erb
<div class='input_form'>
    <h2> Enter your name to create a new game! </h2>
    <p id="notice"><%= notice %></p>

    <%= form_for(@game, :url => play_register_url) do |f| %>
      <div class="field">
        <%= f.label :user_name %><br />
        <%= f.text_field :user_name %>
      </div>
     
      <div class="actions">
        <%= f.submit "New game" %>
      </div>
    <% end %>
</div>