config/routes.rb
ChessMaster::Application.routes.draw do
  resources :games

  resources :boards
  
  match 'play/game(/:slug)' => 'play#game', :as => 'short_game'
  match 'play/register' => 'play#register'
  match 'play/move' => 'play#move'
  match 'play/' => 'play#welcome'
  
  root :to => 'play#welcome'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :boards, :dependent => :delete_all
  before_create :generate_slug
  before_create :set_turn
  before_create :create_board
  validates_presence_of :user_name
  
  def reverse_color(color)
    (color.downcase == 'black') ? 'white' : 'black'
  end
  def computer_color
    reverse_color(self.user_color)
  end
  
  def set_turn
    self.user_color = (rand(2) == 0)? 'black' : 'white' if self.user_color.blank?
    self.user_turn = (self.user_color == 'white')? true : false
    self.turn = 0 if self.turn.blank?
  end
  
  def board
    boards.last
  end
  
  def current_color
    (user_turn) ? user_color : Color.reverse(user_color)
  end
  
  def get_coordinates(position)
    begin
      row = Integer(position[1..1]) - 1
    rescue ArgumentError
      raise MoveError, "Invalid position row: '#{position}'"
    end
    raise MoveError, "Invalid position row: '#{position}'" unless row >= 0 and row < Board::BOARD_WIDTH
    column = position[0..0].ord - 'a'.ord
    raise MoveError, "Invalid position column: '#{position}'" unless column >= 0 and column < Board::BOARD_WIDTH
    [row, column]
  end
  
  def move(from, to, override_checks=false)
    color = current_color
    raise MoveError, "Please fill in two board positions like 'a3' and 'h4'" unless from.size == 2 and to.size == 2
    board = boards.last.dup
    board.turn += 1
    from_row, from_column = get_coordinates(from)
    to_row, to_column = get_coordinates(to)
    board.move(from_row, from_column, to_row, to_column, color, override_checks)
    self.user_turn = (self.user_turn) ? false : true
    self.turn = board.turn
    boards << board
    save
  end
  
  def print_moves(position)
    row, column = get_coordinates(position)
    board.print_moves(row, column)
  end
  
  def pretty_print
    puts "Turn for: #{current_color.to_s.capitalize}"
    board.pretty_print
  end
  
  alias :pp :pretty_print
  
  def auto_move(override_checks=false)
    raise "Can not automove if it's the users turn!" if user_turn and not override_checks
    moves = []
    pieces = board.pieces[current_color.to_sym]
    
    
    pieces.each do |piece|
      moves += piece.valid_moves.map{|f| [piece, f]}
    end
    
    max_hit = 0
    chosen_move = nil
    moves.each do |move|
      piece_value = move[1].piece.value rescue 0
      if piece_value > max_hit
        max_hit = piece_value
        chosen_move = move
      end
    end
    chosen_move = moves[rand(moves.size)] if chosen_move.nil?
        
    piece = chosen_move[0]
    new_field = chosen_move[1]
    old_field = piece.field
    puts "Moving my #{piece.type.capitalize} from #{old_field.name} to #{new_field.name}"
    move(old_field.name, new_field.name)
    self
  end
  
  def create_board
    first_board = Board.start_positions
    first_board.user_turn = self.user_turn
    first_board.turn = 0
    self.boards << first_board
  end
  
  def generate_slug
    self.slug = Digest::MD5::hexdigest("Chess$%^&Master#{rand}") if self.slug.blank?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authorize
  
  def authorize
    raise "Go away"
  end
  # GET /games
  # GET /games.json

  
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  
   <div class="field">
    <%= f.label :user_turn %><br />
    <%= f.select :user_turn, ['black', 'white'] %>
  </div>
  <div class="field">
    <%= f.label :user_turn %><br />
    <%= f.check_box :user_turn %>
  </div>
  <div class="field">
    <%= f.label :turn %><br />
    <%= f.number_field :turn %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class='input_form'>
<h2>Editing game</h2>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table class='listing'>
  <tr>
    <th>User name</th>
    <th>Turn</th>
    <th>User turn</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.user_name %></td>
    <td><%= game.turn %></td>
    <td><%= game.user_turn %></td>
    <td><%= game.slug %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<div class='input_form'>
    <h2>New game</h2>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User name:</b>
  <%= @game.user_name %>
</p>

<p>
  <b>Turn:</b>
  <%= @game.turn %>
</p>
<p>
  <b>User turn:</b>
  <%= @game.user_turn %>
</p>

<p>
  <b>Slug:</b>
  <%= @game.slug %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>