config/routes.rb
ChessMaster::Application.routes.draw do
  resources :games

  resources :boards
  
  match 'play/game(/:slug)' => 'play#game', :as => 'short_game'
  match 'play/register' => 'play#register'
  match 'play/move' => 'play#move'
  match 'play/' => 'play#welcome'
  
  root :to => 'play#welcome'

end

app/models/board.rb
class Board < ActiveRecord::Base
  BOARD_WIDTH = 8
  BOARD_HEIGHT = 8

  belongs_to :game
  validates_presence_of :turn
  before_save :check_rotation
  before_save :serialize_fields
  after_initialize :initialize_fields
  attr_reader :fields, :is_rotated, :pieces
  def initialize_fields
    @is_rotated = false
    empty_fields
    unless self.board.blank?
      load_fields
    end
  end
  
  def get_field(row, column)
    raise RangeError, "Offset out of bounds" if row >= Board::BOARD_HEIGHT or row < 0
    raise RangeError, "Offset out of bounds" if column >= Board::BOARD_WIDTH or column < 0
    @fields[row][column]
  end
  
  
  def dup
    serialize_fields
    result = super
    result.initialize_fields
    result
  end
  
  def rotate
    @fields.reverse!
    @fields.each_with_index do |row, row_index|
      row.reverse!
      row.each_with_index do |field, column_index|
        field.column = column_index
        field.row = row_index
      end
    end
    @is_rotated = (@is_rotated)? false : true
  end

  # if the board is rotated, rotate it back before saving so that we always
  # save the board with white on the bottom
  def check_rotation
    rotate if @is_rotated
  end
  
  def empty_fields
    color = :black
    @fields = []
    (0..(BOARD_HEIGHT - 1)).each do |row|
      @fields[row] = []
      (0..(BOARD_WIDTH - 1)).each do |column|
        color = (color == :black)? :white : :black unless column == 0
        @fields[row][column] = Field.new(color, row, column, self)
      end
    end
  end
  
  def piece= (new_piece)
    new_piece.field = self unless new_piece.nil?
    super(new_piece)
  end
  
  def load_fields
    json_board = JSON.parse(self.board)
    color = :black
    @pieces = {:black => [], :white => []}
    json_board.each_with_index do |row, row_index|
      row.each_with_index do |json_field, column_index|
        field = @fields[row_index][column_index]
        unless json_field.blank?
          piece =  Piece.from_s(json_field)
          piece.move_to field
          @pieces[piece.color.to_sym] << piece
        end
      end
    end
  end

  def self.start_positions
    new_board = Board.new
    start_positions = [
      %w{wr wn wb wq wk wb wn wr},
      %w{wp wp wp wp wp wp wp wp},
      Array.new(6),
      Array.new(6),
      Array.new(6),
      Array.new(6),
      %w{bp bp bp bp bp bp bp bp},
      %w{br bn bb bq bk bb bn br},
     ].to_json
    new_board.board = start_positions
    new_board.load_fields
    new_board
  end
  
  def serialize_fields
    self.board = to_json
    true
  end
  
  def pretty_print(xmarks=[])
    puts "  a  b  c  d  e  f  g  h"
    raise "Can't print if the board is rotated" if @is_rotated
    @fields.reverse.each_with_index do |row, row_index|
      $stdout.print "#{8 - row_index} "
      row.each do |field|
        field_caption = (field.to_s.nil?) ? '..' : field.to_s
        field_caption[1]='X' if xmarks.include? field
        $stdout.print "#{field_caption} "
      end
      puts
    end
    ""
  end
  
  alias :pp :pretty_print
  
  def print_moves(row, column)
    field = get_field(row, column)
    raise MoveError, "No piece at this field!" if field.piece.nil?
    valid_moves = field.piece.valid_moves
    pretty_print(valid_moves)
  end
  
  def to_json
    result = []
    @fields.each_with_index do |row, row_index|
      result[row_index] = []
      row.each_with_index do |field, column_index|
        result[row_index][column_index] = field.to_s  
      end
    end
    result.to_json
  end
  
  def move(from_row,from_column, to_row, to_column, color, skip_checks=false)
    from = fields[from_row][from_column]
    to = fields[to_row][to_column]
    if from.free? or not Color.match(color, from.piece.color)
      raise MoveError, "You don't have a piece at #{from.name}!" unless skip_checks
    end
    if to.occupied? and Color.match(color, to.piece.color)
      raise MoveError, "Tile #{to.name} is already occupied by your #{to.piece.type.capitalize}!" unless skip_checks
    end
    unless from.piece.can_move_to? to
      raise MoveError, "Not a valid move for your #{from.piece.type.capitalize}!" unless skip_checks
    end
    from.piece.move_to to
    self
  end
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :authorize
  
  def authorize
    raise "Go away"
  end
  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
   <div class="field">
    <%= f.label :board %><br />
    <%= f.text_area :board %>
  </div>
  <div class="field">
    <%= f.label :user_turn %><br />
    <%= f.check_box :user_turn %>
  </div>
  <div class="field">
    <%= f.label :turn %><br />
    <%= f.number_field :turn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class='input_form'>
  <h2>Editing board</h2>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>
</div>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table class='listing'>
  <tr>
    <th>Game</th>
    <th>User turn</th>
    <th>Turn</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boards.each do |board| %>
  <tr>
    <td><%= board.game_id %></td>
    <td><%= board.user_turn %></td>
    <td><%= board.turn %></td>
    <td><%= link_to 'Show', board %></td>
    <td><%= link_to 'Edit', edit_board_path(board) %></td>
    <td><%= link_to 'Destroy', board, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<div class='input_form'>
<h2>New board</h2>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>
</div>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @board.game_id %>
</p>

<p>
  <b>User turn:</b>
  <%= @board.user_turn %>
</p>

<p>
  <b>Turn:</b>
  <%= @board.turn %>
</p>


<%= render :partial => "shared/chess_board", :locals => {:board => @board }%>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>