config/routes.rb
ChessMaster::Application.routes.draw do
  resources :games

  resources :boards
  
  match 'play/game(/:slug)' => 'play#game', :as => 'short_game'
  match 'play/register' => 'play#register'
  match 'play/move' => 'play#move'
  match 'play/' => 'play#welcome'
  
  root :to => 'play#welcome'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess Master </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='menu'>
  <div class='buttons'>
      <ol>
          <li>
              <%= link_to games_url do %>
                <span class='indicator'></span>
                <span class='caption'>+ChessMaster</span>
             <%end%>
          </li>
          <li>
              <%= link_to boards_url do %>
                <span class='indicator'></span>
                <span class='caption'>Boards</span>
             <%end%>
          </li>
      </ol>
  
  </div>
  <div class='user_menu'>
     
  </div>
</div>
<div class='header'>
  <div class='header_content'>
    <div class='title'>
      Chess Master
    </div>
    <div class='sub_title'>
      Can you beat the chess master?
    </div>
  </div>
</div>
<div class='body'>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/player.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess Master </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='menu'>
  <div class='buttons'>
   &nbsp;
  </div>
  <div class='user_menu'>
     
  </div>
</div>
<div class='header'>
  <div class='header_content'>
    <div class='title'>
      Chess Master
    </div>
    <div class='sub_title'>
      Can you beat the chess master?
    </div>
  </div>
</div>
<div class='body'>
  <%= yield %>
</div>
</body>
</html>